"""sometext table

Revision ID: 5ac52211a363
Revises: 
Create Date: 2024-04-24 14:13:36.277448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ac52211a363'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('some_text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('some_text', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_some_text_text'), ['text'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('some_text', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_some_text_text'))

    op.drop_table('some_text')
    # ### end Alembic commands ###
